version: 2
jobs:
  build:
    parallelism: 2
    working_directory: /wp-e2e-tests
    docker:
      - image: automattic/wp-e2e-tests:0.0.5
        environment:
                NODE_ENV: test
    steps:
      - checkout
      - restore_cache:
          key: << checksum "package.json" >>
      - run: source $HOME/.nvm/nvm.sh && npm install && npm install -g sitespeed.io@5.5.0
      - save_cache:
          paths:
            - /wp-e2e-tests/node_modules
          key: << checksum "package.json" >>
      - run: ./scripts/randomize.sh specs
      #- run: ./scripts/run-wrapper.sh
      - run:
          name: sitespeed.io tests
          command: sitespeed.io  --budget.configPath ./sitespeed-budget.json -b chrome -n 3 -r ./sitespeed-result --suppressDomainFolder --outputFolderName test http://www.wordpress.com
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: reports/
      - store_artifacts:
          path: screenshots/
      - store_artifacts:
          path: sitespeed-result/