version: 2
jobs:
  build:
    parallelism: 2
    working_directory: /wp-e2e-tests
    docker:
      - image: automattic/wp-e2e-tests:0.0.5
        environment:
                NODE_ENV: test
    steps:
      - checkout
      - restore_cache:
          key: << checksum "package.json" >>
      - run: source $HOME/.nvm/nvm.sh && npm install 
      - save_cache:
          paths:
            - /wp-e2e-tests/node_modules
          key: << checksum "package.json" >>
      - run: ./scripts/randomize.sh specs
      - run: ./scripts/run-wrapper.sh
      - run:
          name: Install Docker
          command: |
            sudo chown -R $(whoami) /usr/local/bin
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/local/bin
      - setup_remote_docker
      - run:
          name: sitespeed.io tests
          command: |
            docker create -v /cfg --name configs alpine:3.4 /bin/true
            docker cp /wp-e2e-tests/sitespeed-budget.json configs:/cfg
            docker run --name sitespeed.io --privileged --shm-size=1g --volumes-from configs -v /cfg:/sitespeed.io sitespeedio/sitespeed.io:5.4.0 -c cable -b chrome --video --speedIndex https://www.wordpress.com --budget.configPath /cfg/sitespeed-budget.json --outputFolder /cfg/sitespeed
            docker cp sitespeed.io:/cfg/sitespeed /wp-e2e-tests/sitespeed-result
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: reports/
      - store_artifacts:
          path: screenshots/
      - store_artifacts:
          path: sitespeed-result/